In [55]:
#Import libraries
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from itertools import product

In [56]:
#Read dataset
df = pd.read_csv('output_1.csv') 
#df = df_original[0:127]
id = pd.DataFrame(df.index + 1)
df.insert (0, "Id", id)
df['age'] = df['age'].map(str)
df['Id'] = df['Id'].map(str)
df

Id age        work_class     education      marital_status  \
0          1  58  Self-emp-not-inc       HS-grad  Married-civ-spouse   
1          2  36           Private       HS-grad  Married-civ-spouse   
2          3  34           Private  Some-college       Never-married   
3          4  50           Private       HS-grad            Divorced   
4          5  42           Private  Some-college           Separated   
...      ...  ..               ...           ...                 ...   
32556  32557  32           Private       Masters  Married-civ-spouse   
32557  32558  45       Federal-gov    Assoc-acdm  Married-civ-spouse   
32558  32559  50           Private       HS-grad  Married-civ-spouse   
32559  32560  44           Private     Bachelors  Married-civ-spouse   
32560  32561  20           Private          11th       Never-married   

             occupation    relationship                race     sex  \
0          Craft-repair         Husband               White    Male   
1       Exec-managerial         Husband               White    Male   
2          Adm-clerical       Own-child               White  Female   
3      Transport-moving   Not-in-family               White    Male   
4         Other-service       Unmarried               Black  Female   
...                 ...             ...                 ...     ...   
32556    Prof-specialty         Husband  Asian-Pac-Islander    Male   
32557   Exec-managerial         Husband               White    Male   
32558      Craft-repair         Husband               White    Male   
32559    Prof-specialty         Husband               White    Male   
32560      Tech-support  Other-relative               White  Female   

       capital_gain  capital_loss  hours_per_week native_country income  \
0                 0             0              20  United-States  <=50K   
1                 0             0              40  United-States  <=50K   
2                 0             0              40  United-States  <=50K   
3                 0             0              40  United-States  <=50K   
4                 0             0              20              *  <=50K   
...             ...           ...             ...            ...    ...   
32556             0             0              40              *  <=50K   
32557             0             0              40  United-States  <=50K   
32558             0             0              45  United-States   >50K   
32559             0             0              45  United-States   >50K   
32560             0             0              30  United-States  <=50K   

        Interests   Looking for  Language  
0           music         forum   Spanish  
1          coding  market place     Tamil  
2        football        advice    Somali  
3             art         forum  Ukranian  
4           tours        advice   Bengali  
...           ...           ...       ...  
32556  literature      hangouts   Arabics  
32557        food        advice   Spanish  
32558   languages   meet people      Bari  
32559        food   meet people   English  
32560    football  things to do   Russian  

[32561 rows x 17 columns]

In [57]:
#Count number of rows and columns in the data set
df.shape

(32561, 17)

In [58]:
#Create a list of important colums for the recommendation engine
columns = ['age', 'Interests', 'Looking for', 'Language']

In [59]:
#Show the data
df[columns].head(3)

age Interests   Looking for Language
0  58     music         forum  Spanish
1  36    coding  market place    Tamil
2  34  football        advice   Somali

In [60]:
#Check for missing values in important columns
df[columns].isnull().values.any()

False

In [61]:
event = ["Sports", "Concerts", "Courses", "Restaurants", "Museums", "Dinnerparty", "Zoo", "Counseling"]
language = ["English", "Russian", "Spanish", "German"]
age_group = ["0-12", "12-18", "21-30", "30-80"]

events = list(product(event,language, age_group))
events
df_events = pd.DataFrame (events, columns = ['Event', "Language", "Age Group"])
df_events

Event Language Age Group
0        Sports  English      0-12
1        Sports  English     12-18
2        Sports  English     21-30
3        Sports  English     30-80
4        Sports  Russian      0-12
..          ...      ...       ...
123  Counseling  Spanish     30-80
124  Counseling   German      0-12
125  Counseling   German     12-18
126  Counseling   German     21-30
127  Counseling   German     30-80

[128 rows x 3 columns]

In [62]:
#Create a function to combine the values of the important columns into a single string of Output1
def get_important_features(data):
    important_features = []
    for i in range(0, df.shape[0]):
        important_features.append(data['Interests'][i]+''+data['Looking for'][i]+''+data['Language'][i]+data['age'][i])
        
    return important_features

In [63]:
#Create column to hold the combined strings
df['important features'] = get_important_features(df)

# Show the data
df.head(3)

Id age        work_class     education      marital_status       occupation  \
0  1  58  Self-emp-not-inc       HS-grad  Married-civ-spouse     Craft-repair   
1  2  36           Private       HS-grad  Married-civ-spouse  Exec-managerial   
2  3  34           Private  Some-college       Never-married     Adm-clerical   

  relationship   race     sex  capital_gain  capital_loss  hours_per_week  \
0      Husband  White    Male             0             0              20   
1      Husband  White    Male             0             0              40   
2    Own-child  White  Female             0             0              40   

  native_country income Interests   Looking for Language  \
0  United-States  <=50K     music         forum  Spanish   
1  United-States  <=50K    coding  market place    Tamil   
2  United-States  <=50K  football        advice   Somali   

          important features  
0        musicforumSpanish58  
1  codingmarket placeTamil36  
2     footballadviceSomali34

In [64]:
#Convert the text to a matrix of taken counts
cm = CountVectorizer().fit_transform(df['important features'])

In [65]:
#Get the cosine similarity matrix from the count matrix
cs = cosine_similarity(cm)
#Print the cosine similarity matrix
print(cs)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [66]:
cs.shape

(32561, 32561)

In [79]:
title = "coding"

#Find the id
user_id = df[df.Interests == title]["Id"].values[0]



In [80]:
#Create a list of enumerations for the similarity score
scores = list(enumerate(cs[user_id]))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [10]:
#Create a function to combine the values of the important columns into a single string
def get_important_features2(df_events):
    important_features = []
    for i in range(0, df_events.shape[0]):
        important_features.append(df_events['Event'][i]+''+df_events['Language'][i]+'')
        
    return important_features

In [11]:
#Create column to hold the combined strings
df_events['important features'] = get_important_features(df_events)

# Show the data
df_events.head(3)

KeyError: 'Interests'

In [28]:
#Convert the text to a matrix of taken counts
cm = CountVectorizer().fit_transform(df_events['important features'])

In [29]:
#Get the cosine similarity matrix from the count matrix
cs = cosine_similarity(cm)
#Print the cosine similarity matrix
print(cs)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]


In [30]:
#Get the shape of the cosine similarity matrix
cs.shape

(128, 128)

In [ ]:
#Get the title of the movie
